# report/html_reporter.py - Standalone HTML reporter for Python.PHP.Whitebox

from __future__ import annotations

import html as html_mod
from typing import Optional

from config.schema import Severity, Confidence
from report.finding import ScanResult, Finding


# ---------------------------------------------------------------------------
# Colour mapping
# ---------------------------------------------------------------------------

_SEV_COLORS: dict[Severity, tuple[str, str]] = {
    # (background, text)
    Severity.CRITICAL: ("#dc2626", "#ffffff"),
    Severity.HIGH:     ("#ef4444", "#ffffff"),
    Severity.MEDIUM:   ("#f59e0b", "#1e1e2e"),
    Severity.LOW:      ("#3b82f6", "#ffffff"),
    Severity.INFO:     ("#6b7280", "#ffffff"),
}

_CONF_COLORS: dict[Confidence, str] = {
    Confidence.HIGH:   "#22c55e",
    Confidence.MEDIUM: "#f59e0b",
    Confidence.LOW:    "#6b7280",
}

_RISK_THRESHOLDS: list[tuple[float, str, str]] = [
    (75, "#dc2626", "Critical"),
    (50, "#f59e0b", "High"),
    (25, "#3b82f6", "Medium"),
    (0,  "#22c55e", "Low"),
]


def _risk_color(score: float) -> str:
    for threshold, color, _ in _RISK_THRESHOLDS:
        if score >= threshold:
            return color
    return "#22c55e"


def _risk_label(score: float) -> str:
    for threshold, _, label in _RISK_THRESHOLDS:
        if score >= threshold:
            return label
    return "Low"


def _esc(text: str) -> str:
    """HTML-escape a string."""
    return html_mod.escape(str(text))


class HTMLReporter:
    """Generates a self-contained HTML report with dark theme."""

    def report(self, result: ScanResult, output_path: Optional[str] = None) -> str:
        """Render the scan result as HTML.

        Returns:
            The path of the generated HTML file.
        """
        html = self._build_html(result)
        path = output_path or "report.html"
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(html)
        return path

    # ------------------------------------------------------------------
    # Top-level document
    # ------------------------------------------------------------------

    def _build_html(self, result: ScanResult) -> str:
        findings_sorted = sorted(
            result.findings,
            key=lambda f: (f.severity, f.confidence),
            reverse=True,
        )
        summary = result.summary

        nav_items = self._build_nav_items(findings_sorted)
        summary_cards = self._build_summary_cards(result)
        risk_section = self._build_risk_section(summary.risk_score if summary else 0.0)
        findings_html = self._build_findings(findings_sorted)
        vuln_type_breakdown = self._build_vuln_type_breakdown(summary)
        errors_html = self._build_errors(result)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Python.PHP.Whitebox Report</title>
<style>
{_CSS}
</style>
</head>
<body>

<!-- Sidebar navigation -->
<nav class="sidebar" id="sidebar">
  <div class="sidebar-header">
    <div class="logo">Python.PHP.Whitebox</div>
    <div class="logo-sub">Security Report</div>
  </div>
  <div class="nav-section">
    <a href="#summary" class="nav-link">Executive Summary</a>
    <a href="#risk" class="nav-link">Risk Score</a>
    <a href="#breakdown" class="nav-link">Vulnerability Types</a>
    <a href="#findings" class="nav-link">Findings ({len(findings_sorted)})</a>
    {nav_items}
    {"<a href='#errors' class='nav-link nav-link-error'>Errors</a>" if result.errors else ""}
  </div>
  <div class="nav-footer">
    v{_esc(result.scanner_version)}
  </div>
</nav>

<!-- Main content -->
<main class="content">

  <!-- Header -->
  <header class="page-header">
    <h1>Python.PHP.Whitebox Security Report</h1>
    <div class="header-meta">
      <span>Project: <strong>{_esc(result.project_path)}</strong></span>
      <span>Scanned: <strong>{_esc(result.timestamp)}</strong></span>
      <span>Duration: <strong>{result.scan_duration_seconds:.2f}s</strong></span>
    </div>
  </header>

  <!-- Executive Summary -->
  <section id="summary">
    <h2>Executive Summary</h2>
    <div class="summary-grid">
      {summary_cards}
    </div>
  </section>

  <!-- Risk Score -->
  <section id="risk">
    <h2>Risk Score</h2>
    {risk_section}
  </section>

  <!-- Vulnerability Type Breakdown -->
  <section id="breakdown">
    <h2>Vulnerability Types</h2>
    {vuln_type_breakdown}
  </section>

  <!-- Findings -->
  <section id="findings">
    <h2>Detailed Findings</h2>
    {findings_html if findings_sorted else '<p class="no-findings">No security findings detected.</p>'}
  </section>

  {errors_html}

  <footer class="report-footer">
    Generated by Python.PHP.Whitebox v{_esc(result.scanner_version)}
  </footer>

</main>

<script>
{_JS}
</script>
</body>
</html>"""

    # ------------------------------------------------------------------
    # Navigation
    # ------------------------------------------------------------------

    def _build_nav_items(self, findings: list[Finding]) -> str:
        items: list[str] = []
        for idx, f in enumerate(findings, 1):
            sev = f.severity.name
            bg, _ = _SEV_COLORS[f.severity]
            items.append(
                f'<a href="#finding-{idx}" class="nav-link nav-finding">'
                f'<span class="nav-sev-dot" style="background:{bg}"></span>'
                f'#{idx} {_esc(f.title[:40])}</a>'
            )
        return "\n    ".join(items)

    # ------------------------------------------------------------------
    # Summary cards
    # ------------------------------------------------------------------

    def _build_summary_cards(self, result: ScanResult) -> str:
        summary = result.summary
        cards: list[str] = []

        # Total findings
        total = summary.total_findings if summary else 0
        cards.append(self._card("Total Findings", str(total), "#a78bfa"))

        # By severity
        for sev in reversed(Severity):
            count = (summary.by_severity.get(sev.name.lower(), 0)) if summary else 0
            bg, _ = _SEV_COLORS[sev]
            cards.append(self._card(sev.name.capitalize(), str(count), bg))

        # Files scanned
        cards.append(self._card("Files Scanned", str(result.files_scanned), "#60a5fa"))

        # Lines of code
        cards.append(self._card("Lines of Code", f"{result.total_lines:,}", "#818cf8"))

        return "\n".join(cards)

    @staticmethod
    def _card(label: str, value: str, accent: str) -> str:
        return (
            f'<div class="summary-card" style="border-top: 3px solid {accent}">'
            f'<div class="card-value" style="color:{accent}">{_esc(value)}</div>'
            f'<div class="card-label">{_esc(label)}</div>'
            f'</div>'
        )

    # ------------------------------------------------------------------
    # Risk score
    # ------------------------------------------------------------------

    def _build_risk_section(self, score: float) -> str:
        color = _risk_color(score)
        label = _risk_label(score)
        pct = max(0, min(100, score))
        return f"""
    <div class="risk-container">
      <div class="risk-score" style="color:{color}">{score:.1f}<span class="risk-max">/100</span></div>
      <div class="risk-label" style="color:{color}">{_esc(label)} Risk</div>
      <div class="risk-bar-outer">
        <div class="risk-bar-inner" style="width:{pct}%;background:{color}"></div>
      </div>
    </div>"""

    # ------------------------------------------------------------------
    # Vulnerability type breakdown
    # ------------------------------------------------------------------

    def _build_vuln_type_breakdown(self, summary) -> str:
        if not summary or not summary.by_vuln_type:
            return '<p class="muted">No vulnerability types to display.</p>'

        rows: list[str] = []
        total = summary.total_findings or 1
        for vuln_type, count in sorted(summary.by_vuln_type.items(), key=lambda x: x[1], reverse=True):
            pct = count / total * 100
            rows.append(
                f'<div class="vuln-row">'
                f'<span class="vuln-name">{_esc(vuln_type)}</span>'
                f'<span class="vuln-count">{count}</span>'
                f'<div class="vuln-bar-outer"><div class="vuln-bar-inner" style="width:{pct:.0f}%"></div></div>'
                f'</div>'
            )
        return f'<div class="vuln-breakdown">{"".join(rows)}</div>'

    # ------------------------------------------------------------------
    # Findings
    # ------------------------------------------------------------------

    def _build_findings(self, findings: list[Finding]) -> str:
        cards: list[str] = []
        for idx, f in enumerate(findings, 1):
            cards.append(self._build_finding_card(idx, f))
        return "\n".join(cards)

    def _build_finding_card(self, idx: int, f: Finding) -> str:
        sev_bg, sev_fg = _SEV_COLORS[f.severity]
        conf_color = _CONF_COLORS[f.confidence]
        sev_name = f.severity.name
        conf_name = f.confidence.name

        location = f"{_esc(f.file_path)}:{f.line}"
        if f.column:
            location += f":{f.column}"

        # Code snippet
        snippet_html = ""
        if f.code_snippet:
            snippet_html = (
                f'<div class="snippet-block">'
                f'<div class="snippet-label">Code</div>'
                f'<pre class="snippet-code">{_esc(f.code_snippet)}</pre>'
                f'</div>'
            )

        # Data flow
        flow_html = ""
        if f.data_flow:
            flow_html = self._build_data_flow(f.data_flow)

        # Remediation
        remediation_html = ""
        if f.remediation:
            remediation_html = (
                f'<div class="remediation-block">'
                f'<div class="remediation-label">Remediation</div>'
                f'<p class="remediation-text">{_esc(f.remediation)}</p>'
                f'</div>'
            )

        # Description
        desc_html = ""
        if f.description:
            desc_html = f'<p class="finding-desc">{_esc(f.description)}</p>'

        return f"""
    <div class="finding-card" id="finding-{idx}">
      <div class="finding-header" onclick="toggleFinding(this)">
        <div class="finding-header-left">
          <span class="sev-badge" style="background:{sev_bg};color:{sev_fg}">{sev_name}</span>
          <span class="conf-badge" style="color:{conf_color}">Conf: {conf_name}</span>
          <span class="cwe-badge">{_esc(f.cwe)}</span>
          {f'<span class="owasp-badge">{_esc(f.owasp)}</span>' if f.owasp else ''}
        </div>
        <div class="finding-header-right">
          <span class="finding-idx">#{idx}</span>
          <span class="toggle-icon">+</span>
        </div>
      </div>
      <div class="finding-title">{_esc(f.title)}</div>
      <div class="finding-location">{location}</div>
      <div class="finding-body" style="display:none">
        {desc_html}
        {snippet_html}
        {flow_html}
        {remediation_html}
        <div class="finding-meta">
          <span>Sink: <code>{_esc(f.sink_function)}</code></span>
          <span>Source: <code>{_esc(f.source_variable)}</code></span>
          <span>Detection: <code>{_esc(f.detection_mode)}</code></span>
          <span>Fingerprint: <code>{_esc(f.fingerprint)}</code></span>
        </div>
      </div>
    </div>"""

    # ------------------------------------------------------------------
    # Data flow trace
    # ------------------------------------------------------------------

    def _build_data_flow(self, steps) -> str:
        items: list[str] = []
        for i, step in enumerate(steps):
            is_first = i == 0
            is_last = i == len(steps) - 1

            if is_first:
                role_class = "flow-source"
                role_label = "SOURCE"
            elif is_last:
                role_class = "flow-sink"
                role_label = "SINK"
            else:
                role_class = "flow-step"
                role_label = "STEP"

            loc = f"{_esc(step.file)}:{step.line}" if step.file else f"line {step.line}"
            desc = _esc(step.description) if step.description else ""
            snippet_part = ""
            if step.snippet:
                snippet_part = f'<pre class="flow-snippet">{_esc(step.snippet)}</pre>'

            items.append(
                f'<div class="flow-item {role_class}">'
                f'<div class="flow-role">{role_label}</div>'
                f'<div class="flow-detail">'
                f'<div class="flow-loc">{loc}</div>'
                f'<div class="flow-desc">{desc}</div>'
                f'{snippet_part}'
                f'</div></div>'
            )

        return (
            f'<div class="flow-block">'
            f'<div class="flow-label">Data Flow</div>'
            f'<div class="flow-list">{"".join(items)}</div>'
            f'</div>'
        )

    # ------------------------------------------------------------------
    # Errors
    # ------------------------------------------------------------------

    def _build_errors(self, result: ScanResult) -> str:
        if not result.errors:
            return ""

        rows: list[str] = []
        for err in result.errors:
            file_path = _esc(err.get("file", "unknown"))
            message = _esc(err.get("message", str(err)))
            rows.append(
                f'<tr><td class="err-file">{file_path}</td><td>{message}</td></tr>'
            )

        return f"""
  <section id="errors">
    <h2 class="errors-heading">Scan Errors ({len(result.errors)})</h2>
    <table class="errors-table">
      <thead><tr><th>File</th><th>Message</th></tr></thead>
      <tbody>{"".join(rows)}</tbody>
    </table>
  </section>"""


# ======================================================================
# Inline CSS  (dark theme, professional)
# ======================================================================

_CSS = """\
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

:root {
  --bg: #0f111a;
  --bg-card: #1a1d2e;
  --bg-sidebar: #141625;
  --bg-input: #232640;
  --text: #e2e8f0;
  --text-dim: #94a3b8;
  --border: #2d3154;
  --accent: #818cf8;
}

body {
  font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
  background: var(--bg);
  color: var(--text);
  line-height: 1.6;
  display: flex;
  min-height: 100vh;
}

/* ---- Sidebar ---- */
.sidebar {
  width: 280px;
  min-width: 280px;
  background: var(--bg-sidebar);
  border-right: 1px solid var(--border);
  position: fixed;
  top: 0;
  left: 0;
  bottom: 0;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  z-index: 100;
}
.sidebar-header {
  padding: 24px 20px 16px;
  border-bottom: 1px solid var(--border);
}
.logo {
  font-size: 1.3rem;
  font-weight: 700;
  color: var(--accent);
  letter-spacing: 0.5px;
}
.logo-sub {
  font-size: 0.8rem;
  color: var(--text-dim);
  margin-top: 2px;
}
.nav-section {
  flex: 1;
  padding: 12px 0;
  overflow-y: auto;
}
.nav-link {
  display: block;
  padding: 8px 20px;
  color: var(--text-dim);
  text-decoration: none;
  font-size: 0.875rem;
  transition: background 0.15s, color 0.15s;
  border-left: 3px solid transparent;
}
.nav-link:hover {
  background: var(--bg-input);
  color: var(--text);
  border-left-color: var(--accent);
}
.nav-finding {
  padding-left: 28px;
  font-size: 0.8rem;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.nav-sev-dot {
  display: inline-block;
  width: 8px;
  height: 8px;
  border-radius: 50%;
  margin-right: 6px;
  vertical-align: middle;
}
.nav-link-error { color: #ef4444; }
.nav-footer {
  padding: 12px 20px;
  font-size: 0.75rem;
  color: var(--text-dim);
  border-top: 1px solid var(--border);
}

/* ---- Main content ---- */
.content {
  margin-left: 280px;
  flex: 1;
  padding: 32px 40px;
  max-width: 1100px;
}

.page-header {
  margin-bottom: 32px;
}
.page-header h1 {
  font-size: 1.8rem;
  font-weight: 700;
  color: var(--accent);
  margin-bottom: 8px;
}
.header-meta {
  display: flex;
  gap: 24px;
  flex-wrap: wrap;
  font-size: 0.875rem;
  color: var(--text-dim);
}
.header-meta strong { color: var(--text); }

section {
  margin-bottom: 40px;
}
h2 {
  font-size: 1.25rem;
  font-weight: 600;
  margin-bottom: 16px;
  padding-bottom: 8px;
  border-bottom: 1px solid var(--border);
  color: var(--text);
}

/* ---- Summary cards ---- */
.summary-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(140px, 1fr));
  gap: 12px;
}
.summary-card {
  background: var(--bg-card);
  border-radius: 8px;
  padding: 16px;
  text-align: center;
}
.card-value {
  font-size: 1.8rem;
  font-weight: 700;
}
.card-label {
  font-size: 0.8rem;
  color: var(--text-dim);
  margin-top: 4px;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

/* ---- Risk score ---- */
.risk-container {
  background: var(--bg-card);
  border-radius: 8px;
  padding: 24px;
  text-align: center;
  max-width: 480px;
}
.risk-score {
  font-size: 3rem;
  font-weight: 800;
}
.risk-max {
  font-size: 1.2rem;
  font-weight: 400;
  opacity: 0.6;
}
.risk-label {
  font-size: 1rem;
  font-weight: 600;
  margin-bottom: 12px;
}
.risk-bar-outer {
  height: 10px;
  background: var(--bg-input);
  border-radius: 5px;
  overflow: hidden;
}
.risk-bar-inner {
  height: 100%;
  border-radius: 5px;
  transition: width 0.5s;
}

/* ---- Vuln type breakdown ---- */
.vuln-breakdown {
  background: var(--bg-card);
  border-radius: 8px;
  padding: 16px;
}
.vuln-row {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 6px 0;
  border-bottom: 1px solid var(--border);
}
.vuln-row:last-child { border-bottom: none; }
.vuln-name {
  flex: 0 0 220px;
  font-size: 0.875rem;
  color: var(--text);
}
.vuln-count {
  flex: 0 0 40px;
  text-align: right;
  font-weight: 600;
  font-size: 0.875rem;
  color: var(--accent);
}
.vuln-bar-outer {
  flex: 1;
  height: 6px;
  background: var(--bg-input);
  border-radius: 3px;
  overflow: hidden;
}
.vuln-bar-inner {
  height: 100%;
  background: var(--accent);
  border-radius: 3px;
}

/* ---- Findings ---- */
.finding-card {
  background: var(--bg-card);
  border-radius: 8px;
  margin-bottom: 12px;
  border: 1px solid var(--border);
  overflow: hidden;
}
.finding-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 12px 16px;
  cursor: pointer;
  user-select: none;
  transition: background 0.15s;
}
.finding-header:hover { background: var(--bg-input); }
.finding-header-left {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-wrap: wrap;
}
.finding-header-right {
  display: flex;
  align-items: center;
  gap: 12px;
}
.sev-badge {
  display: inline-block;
  padding: 2px 10px;
  border-radius: 4px;
  font-size: 0.75rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}
.conf-badge {
  font-size: 0.75rem;
  font-weight: 600;
}
.cwe-badge, .owasp-badge {
  font-size: 0.75rem;
  color: var(--text-dim);
  background: var(--bg-input);
  padding: 2px 8px;
  border-radius: 4px;
}
.finding-idx {
  font-size: 0.8rem;
  color: var(--text-dim);
  font-weight: 600;
}
.toggle-icon {
  font-size: 1.1rem;
  color: var(--text-dim);
  font-weight: 700;
  width: 20px;
  text-align: center;
}

.finding-title {
  padding: 0 16px 4px;
  font-weight: 600;
  font-size: 0.95rem;
}
.finding-location {
  padding: 0 16px 12px;
  font-size: 0.8rem;
  color: var(--text-dim);
  font-family: 'Fira Code', 'Cascadia Code', monospace;
}

.finding-body {
  padding: 0 16px 16px;
  border-top: 1px solid var(--border);
}
.finding-desc {
  margin: 12px 0;
  font-size: 0.875rem;
  color: var(--text-dim);
  line-height: 1.5;
}

/* Code snippet */
.snippet-block { margin: 12px 0; }
.snippet-label, .flow-label, .remediation-label {
  font-size: 0.75rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  color: var(--text-dim);
  margin-bottom: 6px;
}
.snippet-code {
  background: #0d0f17;
  border: 1px solid var(--border);
  border-radius: 6px;
  padding: 12px 16px;
  font-family: 'Fira Code', 'Cascadia Code', monospace;
  font-size: 0.8rem;
  overflow-x: auto;
  color: #e2e8f0;
  line-height: 1.7;
  white-space: pre;
}

/* Data flow */
.flow-block { margin: 12px 0; }
.flow-list {
  border-left: 2px solid var(--border);
  margin-left: 8px;
  padding-left: 0;
}
.flow-item {
  display: flex;
  gap: 12px;
  padding: 8px 0 8px 16px;
  position: relative;
}
.flow-item::before {
  content: '';
  position: absolute;
  left: -6px;
  top: 14px;
  width: 10px;
  height: 10px;
  border-radius: 50%;
  background: var(--border);
}
.flow-source::before { background: #22c55e; }
.flow-sink::before   { background: #ef4444; }
.flow-step::before   { background: #f59e0b; }
.flow-role {
  flex: 0 0 56px;
  font-size: 0.7rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  padding-top: 2px;
}
.flow-source .flow-role { color: #22c55e; }
.flow-sink .flow-role   { color: #ef4444; }
.flow-step .flow-role   { color: #f59e0b; }
.flow-loc {
  font-size: 0.8rem;
  font-family: 'Fira Code', 'Cascadia Code', monospace;
  color: var(--text-dim);
}
.flow-desc {
  font-size: 0.8rem;
  color: var(--text);
}
.flow-snippet {
  background: #0d0f17;
  border: 1px solid var(--border);
  border-radius: 4px;
  padding: 6px 10px;
  font-family: 'Fira Code', 'Cascadia Code', monospace;
  font-size: 0.75rem;
  margin-top: 4px;
  overflow-x: auto;
  color: #e2e8f0;
  white-space: pre;
}

/* Remediation */
.remediation-block {
  margin: 12px 0;
  padding: 12px;
  background: rgba(34,197,94,0.08);
  border: 1px solid rgba(34,197,94,0.2);
  border-radius: 6px;
}
.remediation-text {
  font-size: 0.875rem;
  color: #a7f3d0;
  line-height: 1.5;
}

/* Finding meta */
.finding-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 16px;
  margin-top: 12px;
  font-size: 0.75rem;
  color: var(--text-dim);
}
.finding-meta code {
  background: var(--bg-input);
  padding: 1px 6px;
  border-radius: 3px;
  font-family: 'Fira Code', 'Cascadia Code', monospace;
  font-size: 0.75rem;
}

/* Errors table */
.errors-heading { color: #ef4444 !important; }
.errors-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 0.875rem;
}
.errors-table th {
  text-align: left;
  padding: 8px 12px;
  background: var(--bg-card);
  border-bottom: 1px solid var(--border);
  color: var(--text-dim);
  font-weight: 600;
}
.errors-table td {
  padding: 8px 12px;
  border-bottom: 1px solid var(--border);
}
.err-file {
  font-family: 'Fira Code', 'Cascadia Code', monospace;
  font-size: 0.8rem;
  color: var(--text-dim);
}

.no-findings {
  text-align: center;
  padding: 40px;
  color: #22c55e;
  font-size: 1.1rem;
  font-weight: 600;
}
.muted { color: var(--text-dim); font-size: 0.875rem; }

.report-footer {
  margin-top: 40px;
  padding-top: 16px;
  border-top: 1px solid var(--border);
  font-size: 0.8rem;
  color: var(--text-dim);
  text-align: center;
}

/* Responsive */
@media (max-width: 900px) {
  .sidebar { display: none; }
  .content { margin-left: 0; padding: 16px; }
}
"""

# ======================================================================
# Inline JavaScript (collapsible cards)
# ======================================================================

_JS = """\
function toggleFinding(header) {
  var body = header.parentElement.querySelector('.finding-body');
  var icon = header.querySelector('.toggle-icon');
  if (body.style.display === 'none' || body.style.display === '') {
    body.style.display = 'block';
    icon.textContent = '\\u2212';
  } else {
    body.style.display = 'none';
    icon.textContent = '+';
  }
}

// Smooth scroll for nav links
document.querySelectorAll('.nav-link').forEach(function(link) {
  link.addEventListener('click', function(e) {
    var href = this.getAttribute('href');
    if (href && href.startsWith('#')) {
      e.preventDefault();
      var target = document.querySelector(href);
      if (target) {
        target.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
    }
  });
});
"""
