# report/terminal_reporter.py - ANSI terminal reporter for Python.PHP.Whitebox

from __future__ import annotations

import sys
from typing import Optional

from config.schema import Severity, Confidence
from report.finding import ScanResult, Finding


# ---------------------------------------------------------------------------
# ANSI escape helpers
# ---------------------------------------------------------------------------

class _Colors:
    """ANSI escape sequences.  All attributes resolve to empty strings when
    *no_color* is True so the rest of the code can use them unconditionally."""

    RESET = "\033[0m"
    BOLD = "\033[1m"
    DIM = "\033[2m"
    UNDERLINE = "\033[4m"

    # Foreground
    RED = "\033[91m"
    GREEN = "\033[92m"
    YELLOW = "\033[93m"
    BLUE = "\033[94m"
    MAGENTA = "\033[95m"
    CYAN = "\033[96m"
    WHITE = "\033[97m"
    GRAY = "\033[90m"

    # Backgrounds
    BG_RED = "\033[41m"
    BG_YELLOW = "\033[43m"
    BG_BLUE = "\033[44m"
    BG_MAGENTA = "\033[45m"
    BG_CYAN = "\033[46m"
    BG_GREEN = "\033[42m"
    BG_GRAY = "\033[100m"

    @classmethod
    def disabled(cls) -> "_Colors":
        """Return a proxy where every color attribute is the empty string."""
        obj = cls.__new__(cls)
        for attr in dir(cls):
            if attr.isupper() and not attr.startswith("_"):
                object.__setattr__(obj, attr, "")
        return obj


# Severity -> (color, bg_color, label)
_SEVERITY_STYLE: dict[Severity, tuple[str, str, str]] = {
    Severity.CRITICAL: ("RED", "BG_RED", "CRITICAL"),
    Severity.HIGH:     ("RED", "BG_RED", "HIGH"),
    Severity.MEDIUM:   ("YELLOW", "BG_YELLOW", "MEDIUM"),
    Severity.LOW:      ("CYAN", "BG_CYAN", "LOW"),
    Severity.INFO:     ("GRAY", "BG_GRAY", "INFO"),
}

_CONFIDENCE_STYLE: dict[Confidence, tuple[str, str]] = {
    Confidence.HIGH:   ("GREEN", "HIGH"),
    Confidence.MEDIUM: ("YELLOW", "MEDIUM"),
    Confidence.LOW:    ("GRAY", "LOW"),
}


class TerminalReporter:
    """Prints a coloured terminal report to stdout (or a file)."""

    def __init__(self, no_color: bool = False):
        self.no_color = no_color
        self.c: _Colors = _Colors.disabled() if no_color else _Colors()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def report(self, result: ScanResult, output_path: Optional[str] = None) -> str:
        """Render the scan result to the terminal or a text file.

        Returns:
            The output path if written to a file, or an empty string for stdout.
        """
        lines = self._render(result)
        text = "\n".join(lines) + "\n"

        if output_path:
            with open(output_path, "w", encoding="utf-8") as fh:
                fh.write(text)
            return output_path

        sys.stdout.write(text)
        return ""

    # ------------------------------------------------------------------
    # Internal rendering
    # ------------------------------------------------------------------

    def _render(self, result: ScanResult) -> list[str]:
        c = self.c
        out: list[str] = []

        out.extend(self._banner())
        out.append("")
        out.extend(self._executive_summary(result))
        out.append("")
        out.extend(self._severity_breakdown(result))
        out.append("")

        if result.findings:
            out.extend(self._findings_section(result))
        else:
            out.append(f"  {c.GREEN}{c.BOLD}No findings detected.{c.RESET}")
            out.append("")

        if result.errors:
            out.extend(self._errors_section(result))

        out.append(self._separator())
        out.append(
            f"  {c.DIM}Report generated by Python.PHP.Whitebox v{result.scanner_version}{c.RESET}"
        )
        out.append("")
        return out

    # ------------------------------------------------------------------
    # Banner
    # ------------------------------------------------------------------

    def _banner(self) -> list[str]:
        c = self.c
        lines = [self._separator()]
        lines.append(f"  {c.CYAN}{c.BOLD}PHP Sec Scan{c.RESET}  {c.DIM}— Static Security Scanner for PHP{c.RESET}")
        lines.append(self._separator())
        return lines

    # ------------------------------------------------------------------
    # Executive summary
    # ------------------------------------------------------------------

    def _executive_summary(self, result: ScanResult) -> list[str]:
        c = self.c
        summary = result.summary
        lines: list[str] = []

        lines.append(f"  {c.BOLD}{c.WHITE}EXECUTIVE SUMMARY{c.RESET}")
        lines.append("")

        # Risk score with color coding
        risk = summary.risk_score if summary else 0.0
        risk_color = self._risk_color(risk)
        risk_bar = self._risk_bar(risk)
        lines.append(f"  Risk Score:  {risk_color}{c.BOLD}{risk:.1f}/100{c.RESET}  {risk_bar}")
        lines.append("")

        # Scan metadata
        lines.append(f"  {c.DIM}Project:{c.RESET}       {result.project_path}")
        lines.append(f"  {c.DIM}Duration:{c.RESET}      {result.scan_duration_seconds:.2f}s")
        lines.append(f"  {c.DIM}Files:{c.RESET}         {result.files_scanned} scanned, "
                      f"{result.total_lines:,} lines")
        if summary:
            lines.append(
                f"  {c.DIM}Coverage:{c.RESET}      {summary.files_with_findings} files with findings, "
                f"{summary.files_clean} clean"
            )
        lines.append(
            f"  {c.DIM}Findings:{c.RESET}      {summary.total_findings if summary else 0} total"
        )
        return lines

    # ------------------------------------------------------------------
    # Severity breakdown
    # ------------------------------------------------------------------

    def _severity_breakdown(self, result: ScanResult) -> list[str]:
        c = self.c
        summary = result.summary
        lines: list[str] = []
        lines.append(f"  {c.BOLD}{c.WHITE}FINDINGS BY SEVERITY{c.RESET}")
        lines.append("")

        for sev in reversed(Severity):
            count = (summary.by_severity.get(sev.name.lower(), 0)) if summary else 0
            fg, bg, label = _SEVERITY_STYLE[sev]
            fg_code = getattr(c, fg)
            bg_code = getattr(c, bg)
            bar = self._count_bar(count, summary.total_findings if summary else 0)
            lines.append(
                f"    {bg_code}{c.BOLD}{c.WHITE} {label:^8s} {c.RESET} "
                f"{fg_code}{count:>4d}{c.RESET}  {bar}"
            )

        return lines

    # ------------------------------------------------------------------
    # Findings
    # ------------------------------------------------------------------

    def _findings_section(self, result: ScanResult) -> list[str]:
        c = self.c
        lines: list[str] = []
        lines.append(self._separator())
        lines.append(f"  {c.BOLD}{c.WHITE}DETAILED FINDINGS{c.RESET}")
        lines.append("")

        # Sort by severity descending, then confidence descending
        sorted_findings = sorted(
            result.findings,
            key=lambda f: (f.severity, f.confidence),
            reverse=True,
        )

        for idx, finding in enumerate(sorted_findings, 1):
            lines.extend(self._render_finding(idx, finding))
            lines.append("")

        return lines

    def _render_finding(self, idx: int, f: Finding) -> list[str]:
        c = self.c
        lines: list[str] = []

        # --- Header line: index, severity badge, confidence, CWE ---
        fg, bg, sev_label = _SEVERITY_STYLE[f.severity]
        fg_code = getattr(c, fg)
        bg_code = getattr(c, bg)
        conf_fg, conf_label = _CONFIDENCE_STYLE[f.confidence]
        conf_code = getattr(c, conf_fg)

        lines.append(
            f"  {c.BOLD}#{idx}{c.RESET}  "
            f"{bg_code}{c.BOLD}{c.WHITE} {sev_label} {c.RESET}  "
            f"{conf_code}Confidence: {conf_label}{c.RESET}  "
            f"{c.DIM}{f.cwe}{c.RESET}"
        )

        # --- Title ---
        lines.append(f"      {c.BOLD}{fg_code}{f.title}{c.RESET}")

        # --- Location ---
        location = f"{f.file_path}:{f.line}"
        if f.column:
            location += f":{f.column}"
        lines.append(f"      {c.UNDERLINE}{location}{c.RESET}")

        # --- Description ---
        if f.description:
            lines.append(f"      {c.DIM}{f.description}{c.RESET}")

        # --- Code snippet ---
        if f.code_snippet:
            lines.append("")
            lines.append(f"      {c.DIM}Code:{c.RESET}")
            for snippet_line in f.code_snippet.splitlines():
                lines.append(f"        {c.YELLOW}{snippet_line}{c.RESET}")

        # --- Data flow trace ---
        if f.data_flow:
            lines.append("")
            lines.append(f"      {c.BOLD}Data Flow:{c.RESET}")
            for step_idx, step in enumerate(f.data_flow):
                is_last = step_idx == len(f.data_flow) - 1
                connector = "sink" if is_last else ("source" if step_idx == 0 else "     ")
                prefix_sym = ">>>" if is_last else ("   " if step_idx == 0 else " | ")

                loc = f"{step.file}:{step.line}" if step.file else f"line {step.line}"
                desc = step.description or ""

                if step_idx == 0:
                    # Source
                    lines.append(
                        f"        {c.GREEN}[source]{c.RESET} {c.DIM}{loc}{c.RESET}"
                        f"  {desc}"
                    )
                elif is_last:
                    # Sink
                    lines.append(
                        f"        {c.DIM}  |{c.RESET}")
                    lines.append(
                        f"        {c.RED}[sink]  {c.RESET} {c.DIM}{loc}{c.RESET}"
                        f"  {desc}"
                    )
                else:
                    # Intermediate
                    lines.append(
                        f"        {c.DIM}  |{c.RESET}")
                    lines.append(
                        f"        {c.YELLOW}[step]  {c.RESET} {c.DIM}{loc}{c.RESET}"
                        f"  {desc}"
                    )

                if step.snippet:
                    lines.append(
                        f"                 {c.DIM}{step.snippet}{c.RESET}"
                    )

        # --- Remediation ---
        if f.remediation:
            lines.append("")
            lines.append(f"      {c.GREEN}Remediation:{c.RESET} {f.remediation}")

        # --- Separator ---
        lines.append(f"  {c.DIM}{'- ' * 38}{c.RESET}")

        return lines

    # ------------------------------------------------------------------
    # Errors
    # ------------------------------------------------------------------

    def _errors_section(self, result: ScanResult) -> list[str]:
        c = self.c
        lines: list[str] = []
        lines.append(self._separator())
        lines.append(f"  {c.BOLD}{c.RED}SCAN ERRORS ({len(result.errors)}){c.RESET}")
        lines.append("")
        for err in result.errors:
            file_path = err.get("file", "unknown")
            message = err.get("message", str(err))
            lines.append(f"    {c.RED}!{c.RESET} {c.DIM}{file_path}:{c.RESET} {message}")
        lines.append("")
        return lines

    # ------------------------------------------------------------------
    # Utility helpers
    # ------------------------------------------------------------------

    def _separator(self) -> str:
        c = self.c
        return f"{c.DIM}{'=' * 78}{c.RESET}"

    def _risk_color(self, score: float) -> str:
        c = self.c
        if score >= 75:
            return c.RED
        if score >= 50:
            return c.YELLOW
        if score >= 25:
            return c.CYAN
        return c.GREEN

    def _risk_bar(self, score: float, width: int = 30) -> str:
        c = self.c
        filled = int(score / 100 * width)
        filled = max(0, min(width, filled))
        empty = width - filled
        color = self._risk_color(score)
        return f"{color}{'#' * filled}{c.DIM}{'.' * empty}{c.RESET}"

    def _count_bar(self, count: int, total: int, width: int = 25) -> str:
        c = self.c
        if total == 0:
            return f"{c.DIM}{'.' * width}{c.RESET}"
        filled = int(count / total * width) if total else 0
        filled = max(0, min(width, filled))
        empty = width - filled
        return f"{c.WHITE}{'#' * filled}{c.DIM}{'.' * empty}{c.RESET}"
